FictionFactoryExample2/Models/DrawingsEntity.cs
using MongoDB.Bson.Serialization.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FictionFactoryExample2.Models
{
    public class DrawingsEntity: IDrawingsEntity
    {
        [BsonId]
        [BsonRepresentation(MongoDB.Bson.BsonType.ObjectId)]
        public string _id { get; set; }
        public string Name { get; set; }
        public int Box_Hori_Count { get; set; }
        public decimal Width_row { get; set; }
        public decimal Depth_row { get; set; }
        public int Box_Vert_Count { get; set; }
        public decimal Width_col { get; set; }

        public decimal Height_Col { get; set; }

        public int Box_Back_Count { get; set; }

        public decimal Width_bk { get; set; }

        public decimal Height_bk { get; set; }
       
    }

    public interface IDrawingsEntity
    {
        [BsonId]
        [BsonRepresentation(MongoDB.Bson.BsonType.ObjectId)]
        public string _id { get; set; }
        public string Name { get; set; }
        public int Box_Hori_Count { get; set; }
        public decimal Width_row { get; set; }
        public decimal Depth_row { get; set; }
        public int Box_Vert_Count { get; set; }
        public decimal Width_col { get; set; }

        public decimal Height_Col { get; set; }

        public int Box_Back_Count { get; set; }

        public decimal Width_bk { get; set; }

        public decimal Height_bk { get; set; }

    }
}

FictionFactoryExample2/Models/ErrorViewModel.cs
using System;

namespace FictionFactoryExample2.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FictionFactoryExample2/Controllers/DrawingsController.cs
using FictionFactoryExample2.Interface;
using FictionFactoryExample2.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FictionFactoryExample2.Controllers
{
    public class DrawingsController : Controller
    {
        private readonly IDrawingstore _context;

        public DrawingsController(IDrawingstore context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View(_context.GetAllDrawings());
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreatePost(DrawingsEntity drawingsdata)
        {
            _context.Create(drawingsdata);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Edit(string Name)
        {
            var md = _context.GetDrawingDevDetails(Name);
            return View(md);
        }
        [HttpPost]
        public IActionResult EditPost(string _id,DrawingsEntity drawingsdata)
        {
            _context.Update(_id,drawingsdata);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Details(string Name)
        {
            var md = _context.GetDrawingDevDetails(Name);
            return View(md);
        }
        [HttpGet]
        public IActionResult Delete(string Name)
        {
            var md = _context.GetDrawingDevDetails(Name);
            return View(md);
        }
        [HttpPost]
        public IActionResult DeletePost(string Name)
        {
            _context.Delete(Name);
            return RedirectToAction("Index");
        }
    }
}

FictionFactoryExample2/Controllers/HomeController.cs
using FictionFactoryExample2.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace FictionFactoryExample2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FictionFactoryExample2/Controllers/ValuesController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FictionFactoryExample2.Services;

// For more information on enabling Web API for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860



namespace FictionFactoryExample2.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class ValuesController : ControllerBase
    {
        private readonly DrawingService _drawingService;

        public ValuesController(DrawingService drawingService)
        {
            _drawingService = drawingService;
        }


        // GET: api/<ValuesController>
        [HttpGet]
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET api/<ValuesController>/5
        [HttpGet("{id}")]
        public string Get(string id)
        {
            var drawingsEntity = _drawingService.Get(id);

            if (drawingsEntity == null)
            {
                return "not found";
            }

            return Newtonsoft.Json.JsonConvert.SerializeObject(drawingsEntity);
        }

        // POST api/<ValuesController>
        [HttpPost]
        public Models.DrawingsEntity Post(Models.DrawingsEntity drawingEntity)
        {
            _drawingService.Create(drawingEntity);

            return drawingEntity;

        }

        // PUT api/<ValuesController>/5
        [HttpPut("{id}")]
        public void Put(int id, [FromBody] string value)
        {
        }

        // DELETE api/<ValuesController>/5
        [HttpDelete("{id}")]
        public void Delete(int id)
        {
        }
    }
}

FictionFactoryExample2/Views/Drawings/Create.cshtml
@model FictionFactoryExample2.Models.DrawingsEntity

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>DrawingsEntity</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreatePost">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="_id" class="control-label"></label>
                <input asp-for="_id" class="form-control" />
                <span asp-validation-for="_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Box_Hori_Count" class="control-label"></label>
                <input asp-for="Box_Hori_Count" class="form-control" />
                <span asp-validation-for="Box_Hori_Count" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Width_row" class="control-label"></label>
                <input asp-for="Width_row" class="form-control" />
                <span asp-validation-for="Width_row" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Depth_row" class="control-label"></label>
                <input asp-for="Depth_row" class="form-control" />
                <span asp-validation-for="Depth_row" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Box_Vert_Count" class="control-label"></label>
                <input asp-for="Box_Vert_Count" class="form-control" />
                <span asp-validation-for="Box_Vert_Count" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Width_col" class="control-label"></label>
                <input asp-for="Width_col" class="form-control" />
                <span asp-validation-for="Width_col" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Height_Col" class="control-label"></label>
                <input asp-for="Height_Col" class="form-control" />
                <span asp-validation-for="Height_Col" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Box_Back_Count" class="control-label"></label>
                <input asp-for="Box_Back_Count" class="form-control" />
                <span asp-validation-for="Box_Back_Count" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Width_bk" class="control-label"></label>
                <input asp-for="Width_bk" class="form-control" />
                <span asp-validation-for="Width_bk" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Height_bk" class="control-label"></label>
                <input asp-for="Height_bk" class="form-control" />
                <span asp-validation-for="Height_bk" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FictionFactoryExample2/Views/Drawings/Delete.cshtml
@model FictionFactoryExample2.Models.DrawingsEntity

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DrawingsEntity</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model._id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model._id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Box_Hori_Count)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Box_Hori_Count)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Width_row)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Width_row)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Depth_row)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Depth_row)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Box_Vert_Count)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Box_Vert_Count)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Width_col)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Width_col)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Height_Col)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Height_Col)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Box_Back_Count)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Box_Back_Count)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Width_bk)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Width_bk)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Height_bk)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Height_bk)
        </dd>
    </dl>
    
    <form asp-action="DeletePost">
        <input type="hidden" asp-for="Name" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

FictionFactoryExample2/Views/Drawings/Details.cshtml
@model FictionFactoryExample2.Models.DrawingsEntity

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>DrawingsEntity</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model._id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model._id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Box_Hori_Count)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Box_Hori_Count)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Width_row)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Width_row)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Depth_row)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Depth_row)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Box_Vert_Count)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Box_Vert_Count)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Width_col)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Width_col)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Height_Col)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Height_Col)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Box_Back_Count)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Box_Back_Count)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Width_bk)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Width_bk)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Height_bk)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Height_bk)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

<div id="drawing"></div>

<script src="https://unpkg.com/konva@8/konva.min.js"></script>


<script>

    var model = '@Model.Height_bk'

    var row_width = '@Model.Width_row'

    var row_height = '@Model.Depth_row'

    var row_width = '@Model.Width_row'

    var col_width = '@Model.Width_col'

    var col_height = '@Model.Height_Col'

    var bk_width = '@Model.Width_bk'

    var bk_height = '@Model.Height_bk'




    console.log(model)

    var width = window.innerWidth;
    var height = window.innerHeight;

    var stage = new Konva.Stage({
        container: 'drawing',
        width: width,
        height: height,
    });

    var layer = new Konva.Layer();

    var rect1 = new Konva.Rect({
        x: 20,
        y: 20,
        width: row_width,
        height: row_height,
        fill: 'white',
        stroke: 'black',
       // strokeWidth: 4,
    });
    // add the shape to the layer
    layer.add(rect1);

    var rect2 = new Konva.Rect({
        x: 150,
        y: 400,
        width: col_width,
        height: col_height,
        fill: 'white',
        stroke: 'black',
      //  shadowBlur: 10,
      //  cornerRadius: 10,
    });
    layer.add(rect2);

    var rect3 = new Konva.Rect({
        x: 500,
        y: 120,
        width: bk_width,
        height: bk_height,
        fill: 'white',
        stroke:'black',
        //cornerRadius: [0, 10, 20, 30],
    });
    layer.add(rect3);

    // add the layer to the stage
    stage.add(layer);

</script>

FictionFactoryExample2/Views/Drawings/Edit.cshtml
@model FictionFactoryExample2.Models.DrawingsEntity

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>DrawingsEntity</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditPost">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="_id" class="control-label"></label>
                <input asp-for="_id" class="form-control" />
                <span asp-validation-for="_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Box_Hori_Count" class="control-label"></label>
                <input asp-for="Box_Hori_Count" class="form-control" />
                <span asp-validation-for="Box_Hori_Count" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Width_row" class="control-label"></label>
                <input asp-for="Width_row" class="form-control" />
                <span asp-validation-for="Width_row" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Depth_row" class="control-label"></label>
                <input asp-for="Depth_row" class="form-control" />
                <span asp-validation-for="Depth_row" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Box_Vert_Count" class="control-label"></label>
                <input asp-for="Box_Vert_Count" class="form-control" />
                <span asp-validation-for="Box_Vert_Count" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Width_col" class="control-label"></label>
                <input asp-for="Width_col" class="form-control" />
                <span asp-validation-for="Width_col" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Height_Col" class="control-label"></label>
                <input asp-for="Height_Col" class="form-control" />
                <span asp-validation-for="Height_Col" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Box_Back_Count" class="control-label"></label>
                <input asp-for="Box_Back_Count" class="form-control" />
                <span asp-validation-for="Box_Back_Count" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Width_bk" class="control-label"></label>
                <input asp-for="Width_bk" class="form-control" />
                <span asp-validation-for="Width_bk" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Height_bk" class="control-label"></label>
                <input asp-for="Height_bk" class="form-control" />
                <span asp-validation-for="Height_bk" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FictionFactoryExample2/Views/Drawings/Index.cshtml
@model IEnumerable<FictionFactoryExample2.Models.DrawingsEntity>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model._id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Box_Hori_Count)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Width_row)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Depth_row)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Box_Vert_Count)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Width_col)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Height_Col)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Box_Back_Count)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Width_bk)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Height_bk)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item._id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Box_Hori_Count)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Width_row)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Depth_row)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Box_Vert_Count)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Width_col)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Height_Col)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Box_Back_Count)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Width_bk)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Height_bk)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { Name=item.Name }) |
                @Html.ActionLink("Details", "Details", new { Name = item.Name }) |
                @Html.ActionLink("Delete", "Delete", new { Name = item.Name })
            </td>
        </tr>
}
    </tbody>
</table>

FictionFactoryExample2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

FictionFactoryExample2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FictionFactoryExample2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FictionFactoryExample2</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Drawings" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - FictionFactoryExample2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>